# Generated by Django 6.0.3 on 2026-03-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('patient_name', models.CharField(max_length=255)),
                ('dateofbirth', models.DateField()),
                ('age', models.IntegerField()),
            ],
            options={
                'db_table': 'PATIENTS',
            },
        ),
    ]
